import Pagination from "components/Pagination"
import { SearchContext } from "components/SearchProvider"
import SearchResult from "components/SearchResult"
import { NextPage } from "next"
import Head from "next/head"
import { useContext, useEffect, useState } from "react"
import { getPokemonList } from "services/pokemon"
import { ApiResponseType } from "types"
import styles from "./styles.module.css"

const Home: NextPage = () => {
  const [list, setList] = useState<ApiResponseType>()
  const { state } = useContext(SearchContext)

  useEffect(() => {
    getPokemonList<ApiResponseType>(state).then(setList)
  }, [state])
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Pokedex</h1>
      </header>
      <main className={styles.main}>
        <ul className={styles.list}>
          {list ? (
            list?.results?.map((poke) => (
              <SearchResult data={poke} key={poke.name} />
            ))
          ) : (
            <h2>getting data...</h2>
          )}
        </ul>
      </main>
      <Pagination />
    </>
  )
}

export default Home
