import Pagination from "components/Pagination"
import { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import { getPokemonList } from "services/pokemon"
import { ApiResponseType } from "types"
import styles from "./styles.module.css"

const Home: NextPage = () => {
  const [list, setList] = useState<ApiResponseType>()
  useEffect(() => {
    getPokemonList<ApiResponseType>().then(setList)
  }, [])
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Pokedex</h1>
      </header>
      <main className={styles.main}>
        {list ? (
          list?.results?.map((poke) => <h1>{poke.name}</h1>)
        ) : (
          <h2>getting data...</h2>
        )}
      </main>
      <Pagination />
    </>
  )
}

export default Home
