import ShinyButton from "components/ShinyButton"
import Head from "next/head"
import Image from "next/image"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"
import { getPokemon } from "services/pokemon"
import { PokemonData } from "types"
import styles from "./styles.module.css"

const isNumber = /^[0-9]+$/

const capitalize = (text: string) => {
  return text.charAt(0).toUpperCase() + text.slice(1)
}

export default function PokemonPage() {
  const router = useRouter()
  const [data, setData] = useState<PokemonData>()
  const [shiny, setShiny] = useState<boolean>(false)

  useEffect(() => {
    if (!router.isReady) return
    const { name } = router.query
    getPokemon<PokemonData>(name as string)
      .then((res) => {
        if (isNumber.test(name as string)) {
          router.replace(`/pokemons/${res.name}`)
        }
        setData(res)
      })
      .catch((err) => router.replace("/"))
  }, [router.isReady])

  const handleShiny = () => {
    setShiny(!shiny)
  }

  if (!data) return <h1>loading...</h1>
  return (
    <>
      <Head>
        <title>{capitalize(data.name)} | Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{data.name}</h1>
        <ShinyButton onClick={handleShiny} />
        {shiny ? (
          <section className={styles.sprite_display}>
            <Image src={data.sprites.front_shiny} height={150} width={150} />
            <Image src={data.sprites.back_shiny} height={150} width={150} />
          </section>
        ) : (
          <section className={styles.sprite_display}>
            <Image src={data.sprites.front_default} height={150} width={150} />
            <Image src={data.sprites.back_default} height={150} width={150} />
          </section>
        )}
        <p>base experience: {data.base_experience}</p>
        <p>height: {data.height}</p>
        <p>weight: {data.weight}</p>
        <p>types:</p>
        {data.types.map((info) => (
          <p key={info.type.name}>{info.type.name}</p>
        ))}
        <p>abilities:</p>
        {data.abilities.map((info) => (
          <p key={info.ability.name}>
            {info.ability.name}
            {info.is_hidden && "(h)"}
          </p>
        ))}
        <p>stats:</p>
        {data.stats.map((info) => (
          <p key={info.stat.name}>
            {info.stat.name}: {info.base_stat}
          </p>
        ))}
        <p>held items:</p>
        {data.held_items.length ? (
          data.held_items.map((info) => (
            <p key={info.item.name}>{info.item.name}</p>
          ))
        ) : (
          <p>none</p>
        )}
      </main>
    </>
  )
}
